### ISSUE TITLE
Image Registry Operator reporting it's status to the wrong resource?

### ISSUE THREAD

**Issue by coreydaley** [openshift/cluster-image-registry-operator#115]
If I run "oc get ImageRegistry -o yaml", I see the Image Registry Operator status conditions such as 

  ```
status:
    conditions:
    - lastTransitionTime: 2018-12-11T00:30:49Z
      message: deployment has minimum availability
      status: "True"
      type: Available
    - lastTransitionTime: 2018-12-11T00:30:49Z
      message: everything is ready
      status: "False"
      type: Progressing
    - lastTransitionTime: 2018-12-11T00:30:41Z
      status: "False"
      type: Failing
    - lastTransitionTime: 2018-12-11T00:30:41Z
      status: "False"
      type: Removed
```

But shouldn't these be reported in the ClusterOperator resource?
When I run "oc get ClusterOperator" i see the status for the other operators (including the Samples Operator).  And when I run "oc get ClusterOperator -o yaml" I see similar conditions to what we have in our ImageRegistry resource.  

And then we should be storing things such as the StorageExists condition in the ImageRegistry resource status conditions I would think.

Thoughts?
