### ISSUE TITLE
Is it supported to use PVC as registry storage?

### ISSUE THREAD

**Issue by hongkailiu** [openshift/cluster-image-registry-operator#175]
Is it supported to use PVC as registry storage on OCP 4 like OCP 3?
How do we set it up if yes?

By default, the registry uses s3 on aws.

```
# oc get configs.imageregistry.operator.openshift.io instance -o yaml | grep storageManaged -B3
    s3:
      bucket: image-registry-us-east-2-<hash>
      region: us-east-2
  storageManaged: true

```

Thanks.
