### ISSUE TITLE
Is this the expected way to go to set up (vendor) swift storage for the registry?

### ISSUE THREAD

**Issue by testlaben** [openshift/cluster-image-registry-operator#410]
Currently setting up a 4.2 cluster with IBM Spectrum Scale swift storage.

There seems to be no documentation  or guidelines on how to set this up, but after a fair bit of trial and error; This is what we came up with.

setting up the `image-registry-private-configuration-user` secret with the variables
**REGISTRY_STORAGE_SWIFT_USERNAME** and **REGISTRY_STORAGE_SWIFT_PASSWORD**, and setting 
```yaml
  storage:
    swift:
      authURL: http://storage.example:8888/v3
      authVersion: "3"
      container: ocp-lab-container
      domain: Default
      tenant: ocp-lab
```
Did **not** work.
We were getting Authentication Errors in the operator log, without any more details.

By removing the above secret, and adding the `installer-cloud-credentials` secret instead, with 
a `clouds.yaml`entry:
```yaml
clouds:
  openstack:
    auth:
      auth_url: http://storage.example:8888/v3
      container: ocp-lab-container
      project_name: ocp-lab
      username: ocp-lab
      password: <no passwords in documentation!>
      user_domain_name: Default
      project_domain_name: Default
```
and then adding the following to the `configs.imageregistry.operator.openshift.io`config:

```yaml
spec:
  ...
  storage:
    swift:
      container: ocp-lab-container
```
Sidenote: If you don't specify a container, it will create one for you (which might run you into trouble with permissions)
It will then autopopulate several other fields with details from the `installer-cloud-credentials` secret:
```yaml
  storage:
    swift:
      authURL: http://storage.example:8888/v3
      authVersion: "3"
      container: ocp-lab-container
      domain: Default
      domainID: ""
      regionName: ""
      tenant: ocp-lab
      tenantID: ""
```
And it works!

The operator spams the log with revision changes, not sure if that is a symptom of something else, but atleast it works as expected now...

So, is this the expected way of getting it to work, even with vendor swift (not openstack)?
