### ISSUE TITLE
Upgrade error: Unable to apply 4.2.16: the cluster operator image-registry has not yet successfully rolled out

### ISSUE THREAD

**Issue by dsong1914** [openshift/cluster-image-registry-operator#456]
My cluster upgrade from 4.2 (on VMware) to 4.2.16 failed due to an error with image-registry.  The status of image-registry has been 'updating' for 2 days.  Is this a known bug?  Is there any workaround?  How can I revert its status back to 'available'?

**Comment by bparees** [comment]
Can you provide the full yaml for the registry cluster operator object?

Most likely a registry pod is failing to roll out. You might look at the
state of the deployments and pods in the registry namespace also.

Ben Parees | OpenShift

**Comment by dsong1914** [comment]
One pod under registry namespace is still 'pending' (image-registry-fb9bbcb55-cm2ph).  Attached is the yaml.  

[pod-image-registry-fb9bbcb55-cm2ph.txt](https://github.com/openshift/cluster-image-registry-operator/files/4176432/pod-image-registry-fb9bbcb55-cm2ph.txt)

**Comment by bparees** [comment]
```
status:
  phase: Pending
  conditions:
    - type: PodScheduled
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-02-07T17:01:57Z'
      reason: Unschedulable
      message: persistentvolumeclaim "image-registry-storage" is being deleted
```

seems like an issue w/ your PVs + registry storage configuration.
