### ISSUE TITLE
Pull from ImageStream in Dockerfile - Authentication Required

### ISSUE THREAD

**Issue by reavessm** [openshift/cluster-image-registry-operator#649]
I've been using inline Dockerfiles in build-configs to generate ImageStreams, which is working fine.  I am now trying to build FROM an existing ImageStream in a second Dockerfile, but I am getting errors about Authentication Required.  I would like to know if I am doing something wrong config-wise, if I need to somehow login during the build process, or (what I really want to do) if I can make these images publicly accessible to anybody.

Here is my first yml that builds correctly:

```yml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gentoo
  namespace: gentoo-builder
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "gentoo-build"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
  source:
    dockerfile: |
      # This Dockerfile creates a gentoo stage3 container image. By default it
      # creates a stage3-amd64 image. It utilizes a multi-stage build and requires
      # docker-17.05.0 or later. It fetches a daily snapshot from the official
      # sources and verifies its checksum as well as its gpg signature.

      ARG BOOTSTRAP=alpine:3.12
      FROM --platform=$BUILDPLATFORM ${BOOTSTRAP:-alpine:3.11} as builder

      WORKDIR /gentoo

      ARG ARCH=amd64
      ARG MICROARCH=amd64
      ARG SUFFIX=-hardened
      ARG DIST="https://gentoo.osuosl.org/releases/${ARCH}/autobuilds"
      ARG SIGNING_KEY="0xBB572E0E2D182910"

      RUN echo "Building Gentoo Container image for ${ARCH} ${SUFFIX} fetching from ${DIST}" \
       && apk --no-cache add ca-certificates gnupg tar wget xz \
       && STAGE3PATH="$(wget -O- "${DIST}/latest-stage3-${MICROARCH}${SUFFIX}.txt" | tail -n 1 | cut -f 1 -d ' ')" \
       && echo "STAGE3PATH:" $STAGE3PATH \
       && STAGE3="$(basename ${STAGE3PATH})" \
       && wget -q "${DIST}/${STAGE3PATH}" "${DIST}/${STAGE3PATH}.CONTENTS.gz" "${DIST}/${STAGE3PATH}.DIGESTS.asc" \
       && gpg --list-keys \
       && echo "honor-http-proxy" >> ~/.gnupg/dirmngr.conf \
       && echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf \
       && gpg --keyserver hkps://keys.gentoo.org --recv-keys ${SIGNING_KEY} \
       && gpg --verify "${STAGE3}.DIGESTS.asc" \
       && awk '/# SHA512 HASH/{getline; print}' ${STAGE3}.DIGESTS.asc | sha512sum -c \
       && tar xpf "${STAGE3}" --xattrs-include='*.*' --numeric-owner \
       && ( sed -i -e 's/#rc_sys=""/rc_sys="docker"/g' etc/rc.conf 2>/dev/null || true ) \
       && echo 'America/New_York' > etc/timezone \
       && rm ${STAGE3}.DIGESTS.asc ${STAGE3}.CONTENTS.gz ${STAGE3}

      FROM scratch

      WORKDIR /
      COPY --from=builder /gentoo/ /
      RUN  echo "while (true); do { sleep 3600; }; done" > /dummy-init.sh \
         && chmod +x /dummy-init.sh
      CMD ["/dummy-init.sh"]
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "gentoo:latest"
```

And here is the second yaml that DOES NOT build, due to authentication errors

```yaml
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: gentoo-portage
  namespace: gentoo-builder
spec:
  lookupPolicy:
    local: true
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "gentoo-portage-build"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "ConfigChange"
  source:
    dockerfile: |
      FROM <registryUrl>/gentoo-builder/gentoo:latest

      RUN mkdir -p /etc/portage/repos.conf \
        && cat "[DEFAULT] \
            main-repo = gentoo \
            [gentoo] \
            location = /var/db/repos/gentoo \
            sync-type = git \
            sync-uri = https://anongit.gentoo.org/git/repo/sync/gentoo.git \
            auto-sync = yes \
            sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc \
            sync-openpgp-keyserver = hkps://keys.gentoo.org \
            sync-openpgp-key-refresh-retry-count = 40 \
            sync-openpgp-key-refresh-retry-overall-timeout = 1200 \
            sync-openpgp-key-refresh-retry-delay-exp-base = 2 \
            sync-openpgp-key-refresh-retry-delay-max = 60 \
            sync-openpgp-key-refresh-retry-delay-mult = 4 \
            sync-webrsync-verify-signature = no" > /etc/portage/repos.conf/gentoo.conf \
        && emerge --sync --ask n \
        && emerge -uUDN --with-bdeps=y --jobs 4 --load 4 --keep-going --ask n @world
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      name: "gentoo-portage:latest"
```

My ultimate goal is to create a base builder image to be used when creating images across the cluster.  So I would want to be able to create a new project called `nginx`, and create a buildfile that's something along the lines of `FROM myGentoo RUN emerge nginx`.

I am pretty new to Openshift (running OKD 4.6), so I am more than happy to RTFM, if someone will point me in the right direction
