### ISSUE TITLE
Can't update empty volumeSource to use emptyDir

### ISSUE THREAD

**Issue by dmage** [openshift/cluster-image-registry-operator#91]
The operator doesn't allow to change configuration from
```
  storage:
    filesystem: {}
```
to
```
  storage:
    filesystem:
      volumeSource:
        emptyDir: {}
```
because `storage type change is not supported: expected storage type filesystem, but got emptydir`.

/kind bug
